# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
dist: trusty
latex: false
fortran:false

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: devel
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.2
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
    - libssh-dev

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
