language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - r: devel
    - os: linux
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.3
      brew_packages: libssh
      before_install: brew upgrade libssh # temp fix for outdated travis
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true
    - os: osx
      r: 3.4
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
    - libssh-dev
    - libapparmor-dev

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
