language: r
cache: packages
latex: false
fortran: false

matrix:
  include:
    - os: linux
      dist: trusty
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.2
      brew_packages: libssh
      r:
        - oldrel
        - release
        - devel
    - os: osx
      osx_image: xcode7.3
      disable_homebrew: true

addons:
  apt:
    packages:
    - libssh-dev
    - libapparmor-dev

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
